---
title: "Tests of Goodness-of-Fit"
author: "Sergii Bondariev"
date: "October 21, 2015"
output: html_document
---

```{r global_options, include=FALSE}
#suppress the warnings and other messages from showing in the knitted file.
knitr::opts_chunk$set(fig.width=8, fig.height=6, fig.path='Figs/10.1/',
                      echo=TRUE, warning=FALSE, message=FALSE)
```

```{r, echo=FALSE}
library(ggplot2)
#library(reshape2)
```

# Example 10.1.3

```{r}
# Counts of blood types for white Californians
# A, B, AB, O
observed <- c(2162, 738, 228, 2876)

# Theoretical probabilities of blood types for white Californians
# A, B, AB, O
p0 <- c(1/3, 1/8, 1/24, 1/2)

# Total number of observations
n <- sum(observed)
n

# Expected counts for each group if H0 is true
expected <- n * p0
expected

# Chi-squared statistic
Q <- sum((observed - expected)^2 / expected) 
Q

# Degrees of freedom of the distribution of Q
df <- length(observed) - 1
df

# p-value 
pval = 1 - pchisq(Q, df)
pval

# Alternatively we can use R function
res <- chisq.test(observed, p = p0)
res

# In addition to the main result, there are several other values, 
# for example, the expected theoretical counts for each category
res$expected
```

# Example 10.1.4

```{r}
# Worse, Same, Better
observed = c(58, 64, 67)

n = sum(observed)
k = length(observed)

# Theoretical distribution: uniform
p0 = rep(1/k, k)
p0

chisq.test(observed, p = p0)
```

# Example 10.1.5

```{r}
# 16 out of 100 are defective
n = 100
observed = c(16, n - 16)

p0 = c(0.1, 0.9)

chisq.test(observed, p = p0)

```

# Exercise 10.1.1

```{r}
n = 100
p0 = 0.1
y = seq(0, 100, 1)
f = dbinom(y, n, p0)
ggplot(aes(y, f), data = data.frame(y, f)) +
  geom_point() +
  ggtitle("PMF of binomial distribution with n = 100 and p = 0.1") 
s = 0
c1_ok = -1
c2_ok = -1
for (c1 in seq(-1, n, 1)) {
  for (c2 in seq(c1, n, 1)) {
    s_new = pbinom(c1, n, p0) + (1 - pbinom(c2 - 1, n, p0)) 
    if (s_new > s & s_new <= 0.0455) {
      c1_ok = c1
      c2_ok = c2
      s = s_new
    }
  }
}

s
c1_ok
c2_ok

p = seq(0, 1, 0.01)
f = pbinom(c1_ok, n, p) + (1 - pbinom(c2_ok - 1, n, p)) 
ggplot(aes(p, f), data = data.frame(p, f)) +
  geom_line() +
  geom_vline(x = p0, color = 'blue') +
  geom_text(aes(p0, 0, label = p0, hjust = 1.2)) +
  geom_hline(y = s, color = 'red') + 
  geom_text(aes(0, s, label = round(s, digits = 4), vjust = -1)) +
  xlab("Possible value of the parameter of the Bernoulli distribution observations come from") +
  ylab("Power function") +
  ggtitle("Graph of the power function")
```

