---
title: "Problems of Testing Hypotheses"
author: "Sergii Bondariev"
date: "October 21, 2015"
output: html_document
---

```{r global_options, include=FALSE}
#suppress the warnings and other messages from showing in the knitted file.
knitr::opts_chunk$set(fig.width=8, fig.height=6, fig.path='Figs/9.1/',
                      echo=TRUE, warning=FALSE, message=FALSE)
```

```{r, echo=FALSE}
library(ggplot2)
#library(reshape2)
```

# Exercise 9.11

## a.

```{r}
n = 9
p0 = 0.4
s = 0
c1_ok = -1
c2_ok = -1
for (c1 in seq(-1, n, 1)) {
  for (c2 in seq(c1, n, 1)) {
    s_new = pbinom(c1, n, p0) + (1 - pbinom(c2 - 1, n, p0)) 
    if (s_new > s & s_new <= 0.1) {
      c1_ok = c1
      c2_ok = c2
      s = s_new
    }
  }
}

s
c1_ok
c2_ok
```

## b. 
The size of the test is s, calculated in part (a).

## c.
```{r}
p = seq(0, 1, 0.01)
f = pbinom(c1_ok, n, p) + (1 - pbinom(c2_ok - 1, n, p)) 
ggplot(aes(p, f), data = data.frame(p, f)) +
  geom_line() +
  geom_vline(x = p0, color = 'blue') +
  geom_text(aes(p0, 0, label = p0, hjust = 1.2)) +
  geom_hline(y = s, color = 'red') + 
  geom_text(aes(0, s, label = round(s, digits = 4), vjust = -1)) +
  xlab("Possible value of the parameter of the Bernoulli distribution observations come from") +
  ylab("Power function") +
  ggtitle("Graph of the power function")
```



```{r}
```
```{r}
```
```{r}
```
```{r}
```
```{r}
```
```{r}
```
```{r}
```
```{r}
```
```{r}
```
```{r}
```

```{r, echo=FALSE}
#scale_y_continuous(breaks = sort(c(seq(min(df$y), max(df$y), length.out=5), h)))
```

